Repository dnd-side-project/dnd-7th-1-iOS, pull requests merged in 2023-04, with the labels that each got.

#122 Add/#121 signup parameter
  NEMODU/NEMODU/Global/Extension/UserDefaults+.swift
  NEMODU/NEMODU/Screen/Login/Model/UserDataModel.swift
  NEMODU/NEMODU/Screen/Login/ViewModel/LoginVM.swift
Labels: 윤경, Feature, Network, 로그인/회원가입

#128 Chore/#127 signup endpoint
  NEMODU/NEMODU/Screen/Login/Model/UserDataModel.swift
  NEMODU/NEMODU/Screen/Login/ViewModel/EnterVM.swift
Labels: 윤경, Network, 로그인/회원가입

#113 Feat/#106 챌린지 상세지도 화면 구현
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/ChallengeColorType.swift
  NEMODU/NEMODU/Global/Enum/ChallengeType.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/ChallengeDetailMapResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/View/ChallengeDetailInfoView.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMapVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMiniMapVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeHistoryDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/DoneChallengeDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/InvitedChallengeDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/ChallengeFinishTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/ChallengeDetailTVFV.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/HV/ChallengeHistoryDetailTVHV.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/HV/InvitedChallengeDetailTVHV.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewModel/Challenge/ChallengeDetailMapVM.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MapVC.swift
  NEMODU/NEMODU/Screen/Share/View/Matrix.swift
  NEMODU/NEMODU/Screen/Share/View/MenuBarCV.swift
  NEMODU/NEMODU/Screen/Share/View/MenuBarCVC.swift
  NEMODU/NEMODU/Screen/Share/View/NavigationBar.swift
  NEMODU/NEMODU/Screen/Share/View/NicknameModel.swift
  NEMODU/NEMODU/Screen/Share/View/TabCVC.swift
  NEMODU/NEMODU/Screen/Share/View/TabView.swift
  NEMODU/Podfile
  NEMODU/Podfile.lock
Labels: 희재, 랭킹/챌린지, Feature, View, Network, Refactor, 챌린지

#126 Feat/#115 푸시알림 기능 구현
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/AlertType.swift
  NEMODU/NEMODU/Global/Enum/NotificationCategoryType.swift
  NEMODU/NEMODU/NEMODU.entitlements
  NEMODU/NEMODU/Screen/Mypage/View/SettingItemTitleLabelView.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/MypageVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/SetNotificationVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/SetPrivacyVC.swift
  NEMODU/NEMODU/Screen/Share/View/AlertVC.swift
  NEMODU/NEMODU/Support/AppDelegate.swift
  NEMODU/NEMODU/Support/Info.plist
  NEMODU/Podfile
  NEMODU/Podfile.lock
Labels: 희재, Feature, Network, 로그인/회원가입

#134 Feat/#132 푸시알림 화면전환 서버연동
  NEMODU/NEMODU/Global/Enum/NotificationCategoryType.swift
  NEMODU/NEMODU/Support/AppDelegate.swift
Labels: 희재, 랭킹/챌린지, 마이페이지, Feature, Network

#138 Feat/#123 map constants struct
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Screen/Map/Model/Map.swift
  NEMODU/NEMODU/Screen/Map/Model/Response/ChallengeBlockResponseModel.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MainVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MapVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/WalkingVC.swift
  NEMODU/NEMODU/Screen/Map/ViewModel/MainVM.swift
  NEMODU/NEMODU/Screen/Map/ViewModel/WalkingVM.swift
  NEMODU/NEMODU/Screen/Share/View/MiniMapVC.swift
  NEMODU/Podfile.lock
Labels: 윤경, 지도, Feature, Refactor

#140 Fix/#139-GoogleService-Info.plist 파일 누락 수정
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/GoogleService-Info.plist
Labels: bug, HOTFIX

#129 Refactor/#117 Request & Response값 변경 수정반영
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/ChallengeType.swift
  NEMODU/NEMODU/Global/Enum/InvitedChallengeAcceptType.swift
  NEMODU/NEMODU/Global/Extension/Date+.swift
  NEMODU/NEMODU/Global/Extension/Int+.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/AcceptRejectChallengeResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/ChallengeDetailMapResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/ChallengeHistoryDetailResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/CreatChallengeResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/FriendsListResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/InvitedChallengeDetailResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Challenge/Response/InvitedChallengeListResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Ranking/Request/RankingListRequestModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Ranking/Response/AccumulateRankingListResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Ranking/Response/AreaRankingListResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/Model/Ranking/Response/StepRankingListResponseModel.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMapVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeHistoryDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/InvitedChallengeDetailVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/ChallengeDoingTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/ChallengeFinishTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/ChallengeListTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/ChallengeWaitingTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/InvitedChallengeTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/Cell/InvitedFriendsTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/HV/ChallengeDetailTVHV.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeTV/HV/InvitedChallengeDetailTVHV.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/ChallengePeriodVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/CreateAccumulateChallengeVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/CreateChallengeSuccuessVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/CreateWeekChallengeVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/CreateWidenChallengeVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/CreateWeekChallenge/SelectFriendsVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/View/FriendListView.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/CreateChallenge/View/SelectFriendsTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Ranking/AccumulateRankingListVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Ranking/AreaRankingListVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Ranking/RankingTV/RankingUserTVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Ranking/StepRankingListVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewModel/Challenge/InvitedChallengeDetailVM.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewModel/Ranking/AreaRankingListVM.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewModel/Ranking/StepRankingListVM.swift
Labels: bug, 희재, 랭킹/챌린지, Network, Refactor, 챌린지, 랭킹

#131 Feat/#130 이용약관 동의 & 권한설정 화면 구성
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Screen/Login/View/TermsConditionsDetailButton.swift
  NEMODU/NEMODU/Screen/Login/ViewController/SetAuthorityVC.swift
  NEMODU/NEMODU/Screen/Login/ViewController/TermsConditionsAgreementVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/MypageVC.swift
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/AllInbox.imageset/All inbox@1x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/AllInbox.imageset/All inbox@2x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/AllInbox.imageset/All inbox@3x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/AllInbox.imageset/Contents.json
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/CameraAlt.imageset/Camera alt@1x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/CameraAlt.imageset/Camera alt@2x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/CameraAlt.imageset/Camera alt@3x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/CameraAlt.imageset/Contents.json
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/Contents.json
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/LocationOn.imageset/Contents.json
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/LocationOn.imageset/Location on@1x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/LocationOn.imageset/Location on@2x.png
  NEMODU/NEMODU/Support/Assets.xcassets/AuthorityIconList/LocationOn.imageset/Location on@3x.png
  NEMODU/NEMODU/Support/Assets.xcassets/arrow_right.imageset/arrow_right@1x.png
  NEMODU/NEMODU/Support/Assets.xcassets/arrow_right.imageset/arrow_right@2x.png
  NEMODU/NEMODU/Support/Assets.xcassets/arrow_right.imageset/arrow_right@3x.png
Labels: 희재, Feature, View, 로그인/회원가입

#141 Feat/#136 사용자 알림 설정 서버연결
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/NotificationCategoryType.swift
  NEMODU/NEMODU/Screen/Mypage/Model/Request/UpdateNotificationSettingRequestModel.swift
  NEMODU/NEMODU/Screen/Mypage/Model/Response/SetNotificationResponseModel.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/SetNotificationVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewModel/SetNotificationVM.swift
  NEMODU/Podfile.lock
Labels: 희재, 마이페이지, Network

#147 Feat/#144 이용약관 웹페이지 주소 변경
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/TermsConditionsWebLink.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/MypageVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/TermsConditionsVC.swift
Labels: 희재, 마이페이지, Feature, View

#142 Refactor/#133 map rendering hang
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Screen/Map/Model/Block/Area.swift
  NEMODU/NEMODU/Screen/Map/Model/Block/Block.swift
  NEMODU/NEMODU/Screen/Map/Model/Map.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MainVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MapVC.swift
  NEMODU/NEMODU/Support/GoogleService-Info.plist
Labels: 윤경, 지도, HOTFIX, View, Refactor

#150 Add/#149 friend profile
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Enum/FriendStatusType.swift
  NEMODU/NEMODU/Global/Enum/ToastType.swift
  NEMODU/NEMODU/Global/Extension/UIViewController+.swift
  NEMODU/NEMODU/Screen/Map/Model/Request/FriendRequestModel.swift
  NEMODU/NEMODU/Screen/Map/ViewController/BottomSheet/FriendProfileBottomSheet.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MainVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MapVC.swift
  NEMODU/NEMODU/Screen/Map/ViewModel/FriendProfileVM.swift
  NEMODU/NEMODU/Screen/Share/View/ToastView.swift
Labels: 윤경, 지도, Network, Refactor

#153 [FIX] : self 문법 오류 수정
  NEMODU/NEMODU/Screen/Login/ViewController/TermsConditionsAgreementVC.swift
Labels: 희재, HOTFIX, 로그인/회원가입

#154 Fix/#145 챌린지 알림 액션 수정
  NEMODU/NEMODU/Support/AppDelegate.swift
Labels: 희재, 챌린지

#156 Refactor/#155 네모두 이용약관 웹링크 관리방식 변경
  NEMODU/NEMODU/Global/Enum/TermsConditionsWebLink.swift
  NEMODU/NEMODU/Screen/Login/ViewController/TermsConditionsAgreementVC.swift
  NEMODU/NEMODU/Screen/Mypage/ViewController/TermsConditionsVC.swift
Labels: 희재, Refactor, 로그인/회원가입

#157 Feat/#151 loading view
  NEMODU/NEMODU.xcodeproj/project.pbxproj
  NEMODU/NEMODU/Global/Class/BaseViewController.swift
  NEMODU/NEMODU/Global/Extension/UIColor+.swift
  NEMODU/NEMODU/Global/Utils/Lottie/loading.json
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewController/Challenge/ChallengeDetail/ChallengeDetailMapVC.swift
  NEMODU/NEMODU/Screen/ChallengeRanking/ViewModel/Challenge/ChallengeDetailMapVM.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MainVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/MyDetailMapVC.swift
  NEMODU/NEMODU/Screen/Map/ViewController/WalkingVC.swift
  NEMODU/NEMODU/Screen/Map/ViewModel/MainVM.swift
  NEMODU/NEMODU/Screen/Map/ViewModel/WalkingVM.swift
  NEMODU/NEMODU/Screen/Mypage/ViewModel/MypageVM.swift
  NEMODU/NEMODU/Screen/Share/View/AlertVC.swift
  NEMODU/NEMODU/Screen/Share/View/LoadingView.swift
  NEMODU/Podfile.lock
Labels: 윤경, Feature, View, Network
